"""
build_spec_slim.py — Build allégé SANS modèles whisper embarqués.
Les modèles sont téléchargés automatiquement au premier lancement via HuggingFace.
Output : dist/MeetNote-slim  (~300-400 MB au lieu de 3.2 GB)
"""

import os
import sys
import subprocess
import shutil as _shutil

# ─── Paths ───────────────────────────────────────────────────────────────────
SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
VENV        = os.path.join(os.path.dirname(os.path.dirname(SCRIPT_DIR)), ".venv")
SITE_PKG    = os.path.join(VENV, "Lib", "site-packages")

# ─── Datas : pas de modèles, uniquement les assets runtime ───────────────────
datas_lines = []

# faster_whisper assets (silero_vad_v6.onnx)
fw_assets = os.path.join(SITE_PKG, "faster_whisper", "assets")
if os.path.isdir(fw_assets):
    datas_lines.append(f"    (r'{fw_assets.replace(chr(92), '/')}', 'faster_whisper/assets'),")

# sounddevice portaudio DLLs
sd_data = os.path.join(SITE_PKG, "_sounddevice_data")
if os.path.isdir(sd_data):
    datas_lines.append(f"    (r'{sd_data.replace(chr(92), '/')}', '_sounddevice_data'),")

# ctranslate2
ct2_dir = os.path.join(SITE_PKG, "ctranslate2")
if os.path.isdir(ct2_dir):
    datas_lines.append(f"    (r'{ct2_dir.replace(chr(92), '/')}', 'ctranslate2'),")

# tokenizers
tk_dir = os.path.join(SITE_PKG, "tokenizers")
if os.path.isdir(tk_dir):
    datas_lines.append(f"    (r'{tk_dir.replace(chr(92), '/')}', 'tokenizers'),")

# soundcard
sc_dir = os.path.join(SITE_PKG, "soundcard")
if os.path.isdir(sc_dir):
    datas_lines.append(f"    (r'{sc_dir.replace(chr(92), '/')}', 'soundcard'),")

# ffmpeg + ffprobe
for _bin in ("ffmpeg.exe", "ffprobe.exe"):
    _found = _shutil.which(_bin.replace(".exe", "")) or _shutil.which(_bin)
    if _found:
        datas_lines.append(f"    (r'{_found.replace(chr(92), '/')}', r'.'),")
        print(f"[build_slim] Bundling {_bin}: {_found}")
    else:
        print(f"[build_slim] {_bin} not found — audio conversion requires ffmpeg at runtime")

datas_block = "\n".join(datas_lines)

# ─── Hidden imports (identiques au build complet) ────────────────────────────
hidden_imports = [
    "soundcard", "soundcard.mediafoundation",
    "sounddevice", "_sounddevice", "_sounddevice_data",
    "faster_whisper", "faster_whisper.audio", "faster_whisper.feature_extractor",
    "faster_whisper.tokenizer", "faster_whisper.transcribe",
    "faster_whisper.utils", "faster_whisper.vad",
    "ctranslate2", "tokenizers", "tokenizers.models", "tokenizers.normalizers",
    "tokenizers.pre_tokenizers", "tokenizers.processors", "tokenizers.decoders",
    "pystray", "pystray._win32",
    "PIL", "PIL.Image", "PIL.ImageDraw", "PIL.ImageFont", "PIL._imaging",
    "tkinter", "tkinter.ttk",
    "huggingface_hub", "huggingface_hub.file_download",
    "numpy", "av", "onnxruntime", "onnxruntime.capi", "cffi",
    "notion_push", "config", "user_config", "history", "outlook_cal",
    "teams_roster", "soundfile", "_soundfile",
    "wave", "glob", "json", "collections", "dataclasses", "shutil",
    "scipy", "scipy.signal", "noisereduce",
    "pycaw", "pycaw.pycaw", "comtypes", "psutil",
    "win32com", "win32com.client", "pywintypes",
]
hidden_imports_str = ",\n    ".join(f"'{h}'" for h in hidden_imports)

# ─── Spec ────────────────────────────────────────────────────────────────────
ENTRY_POINT = os.path.join(SCRIPT_DIR, "meetnote-tray.py").replace("\\", "/")
DIST_NAME   = "MeetNote-slim"

spec_content = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_spec_slim.py — do not edit manually

import sys
from PyInstaller.utils.hooks import collect_all

block_cipher = None

ct2_datas, ct2_binaries, ct2_hiddenimports = collect_all('ctranslate2')
sd_datas, sd_binaries, sd_hiddenimports   = collect_all('sounddevice')

a = Analysis(
    [r'{ENTRY_POINT}'],
    pathex=[r'{SCRIPT_DIR.replace(chr(92), "/")}'],
    binaries=ct2_binaries + sd_binaries,
    datas=[
{datas_block}
    ] + ct2_datas + sd_datas,
    hiddenimports=[
    {hidden_imports_str},
    ] + ct2_hiddenimports + sd_hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['pandas', 'jupyter', 'IPython', 'PyQt5', 'wx'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MeetNote',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='{DIST_NAME}',
)
"""

spec_path = os.path.join(SCRIPT_DIR, "meetnote-slim.spec")
with open(spec_path, "w", encoding="utf-8") as f:
    f.write(spec_content)
print(f"[build_slim] Wrote {spec_path}")

# ─── Run PyInstaller ──────────────────────────────────────────────────────────
print("[build_slim] Starting PyInstaller build (no models)...")
pyinstaller_exe = os.path.join(VENV, "Scripts", "pyinstaller.exe")
if not os.path.exists(pyinstaller_exe):
    pyinstaller_exe = "pyinstaller"

result = subprocess.run(
    [pyinstaller_exe, "--clean", "--noconfirm", spec_path],
    cwd=SCRIPT_DIR,
    capture_output=False,
)

if result.returncode != 0:
    print(f"\n[build_slim] FAILED (exit {result.returncode})")
    sys.exit(result.returncode)

dist_dir = os.path.join(SCRIPT_DIR, "dist", DIST_NAME)

# ─── Taille finale ───────────────────────────────────────────────────────────
total = sum(
    os.path.getsize(os.path.join(r, f))
    for r, _, files in os.walk(dist_dir)
    for f in files
)
count = sum(len(files) for _, _, files in os.walk(dist_dir))
print(f"\n[build_slim] SUCCESS — {dist_dir}")
print(f"[build_slim] {count} files, {total / 1024 / 1024:.1f} MB")

# ─── Zip pour GitHub Release ─────────────────────────────────────────────────
zip_path = os.path.join(SCRIPT_DIR, "dist", "MeetNote-slim")
print(f"[build_slim] Creating zip {zip_path}.zip ...")
import shutil as _shutil2
_shutil2.make_archive(zip_path, "zip", os.path.join(SCRIPT_DIR, "dist"), DIST_NAME)
zip_size = os.path.getsize(zip_path + ".zip") / 1024 / 1024
print(f"[build_slim] Zip ready: {zip_path}.zip ({zip_size:.1f} MB)")
