# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_spec.py — do not edit manually

import sys
from PyInstaller.utils.hooks import collect_all, collect_data_files

block_cipher = None

# Collect all from ctranslate2 (picks up DLLs via hook)
ct2_datas, ct2_binaries, ct2_hiddenimports = collect_all('ctranslate2')
sd_datas, sd_binaries, sd_hiddenimports   = collect_all('sounddevice')

a = Analysis(
    [r'H:/DEV/meetnote/pc/meetnote-tray.py'],
    pathex=[r'H:/DEV/meetnote/pc'],
    binaries=ct2_binaries + sd_binaries,
    datas=[
    (r'C:/Users/potti/.cache/huggingface/hub/models--Systran--faster-whisper-base/snapshots/ebe41f70d5b6dfa9166e2c581c45c9c0cfc57b66', r'faster_whisper_models/base'),
    (r'C:/Users/potti/.cache/huggingface/hub/models--Systran--faster-whisper-small/snapshots/536b0662742c02347bc0e980a01041f333bce120', r'faster_whisper_models/small'),
    (r'H:/DEV/.venv/Lib/site-packages/faster_whisper/assets', 'faster_whisper/assets'),
    (r'H:/DEV/.venv/Lib/site-packages/_sounddevice_data', '_sounddevice_data'),
    (r'H:/DEV/.venv/Lib/site-packages/ctranslate2', 'ctranslate2'),
    (r'H:/DEV/.venv/Lib/site-packages/tokenizers', 'tokenizers'),
    (r'H:/DEV/.venv/Lib/site-packages/soundcard', 'soundcard'),
    ] + ct2_datas + sd_datas,
    hiddenimports=[
    'soundcard',
    'soundcard.mediafoundation',
    'sounddevice',
    '_sounddevice',
    '_sounddevice_data',
    'faster_whisper',
    'faster_whisper.audio',
    'faster_whisper.feature_extractor',
    'faster_whisper.tokenizer',
    'faster_whisper.transcribe',
    'faster_whisper.utils',
    'faster_whisper.vad',
    'ctranslate2',
    'tokenizers',
    'tokenizers.models',
    'tokenizers.normalizers',
    'tokenizers.pre_tokenizers',
    'tokenizers.processors',
    'tokenizers.decoders',
    'pystray',
    'pystray._win32',
    'PIL',
    'PIL.Image',
    'PIL.ImageDraw',
    'PIL.ImageFont',
    'PIL._imaging',
    'tkinter',
    'tkinter.ttk',
    'huggingface_hub',
    'numpy',
    'av',
    'onnxruntime',
    'onnxruntime.capi',
    'cffi',
    'notion_push',
    'config',
    ] + ct2_hiddenimports + sd_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'scipy', 'pandas', 'jupyter', 'IPython', 'PyQt5', 'wx'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MeetNote',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,          # no console window (tray app)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='MeetNote',
)
